AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 100
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    MemorySize: 512
    Environment:
      Variables:
        SAMPLE_TABLE: !Ref SampleTable

Resources:
  GetNotesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.getNotes
      Events:
        GetNotes:
          Type: Api
          Properties:
            Path: /notes
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

  GetNoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.getNote
      Events:
        GetNote:
          Type: Api
          Properties:
            Path: /notes/{id}
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

  DeleteNoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.deleteNote
      Events:
        DeleteNote:
          Type: Api
          Properties:
            Path: /notes/{id}
            Method: DELETE
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

  CreateNoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.createNote
      Events:
        CreateNote:
          Type: Api
          Properties:
            Path: /notes
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

  UpdateNoteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.updateNote
      Events:
        UpdateNote:
          Type: Api
          Properties:
            Path: /notes
            Method: PUT
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SampleTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

  SampleTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
